[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
simple_storage = "NgoV63pHvHu6AE8oQ4XzRMt4A4DGXmuEF7SY1RxQf9W"

[programs.localnet]
simple_storage = "NgoV63pHvHu6AE8oQ4XzRMt4A4DGXmuEF7SY1RxQf9W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com "
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
